### ISSUE TITLE
No stack trace when errors are thrown

### ISSUE THREAD

**Issue by wagnerpaul** [afbora/kirby-blade#10]
The errors that blade throws are often useless because there is no real stack trace.  Although there is no real stack trace it will produce a hint as to which view had the error in the top level error **but only if you use a laravel directive to include it**.  If you use a kirby snippet() helper you will only see an error with no stack trace and a reference to the blade template that called it.

**Comment by afbora** [comment]
@wagnerpaul You're right! The plugin had a lack of debugging, but I corrected it in the last version as v1.5.1+. Is it still continue?

**Comment by afbora** [comment]
Feel free to repoen the issue still continue
