### ISSUE TITLE
Illuminate/Kirby redeclaring the `e()` function

### ISSUE THREAD

**Issue by adamkiss** [afbora/kirby-blade#11]
Just installed this plugin, I can't even load a page (any page), because there is a conflict with the `e()` function between Kirby and Illuminate.

```
PHP Fatal error:  Cannot redeclare e() (previously declared in /---/vendor/illuminate/support/helpers.php:607) in /---/kirby/config/helpers.php on line 162
```

I have absolutely no idea how to deal with this.

Thank you

**Comment by adamkiss** [comment]
Ah, now I saw the [issue on the Kirby Forum](https://forum.getkirby.com/t/problem-using-blade-plugin/14853/26) - should I close this one?

For posterity - the issue is that if the composer creates an autoloader where kirby's `e()` function isn't created first, PHP will fail with `FATAL_ERROR`.

Since you can't force the composer to use a load order AFAIK, the only solution seems to be to download this plugin to site/plugins or use git submodule as a way of includeing this plugin.

**Comment by afbora** [comment]
as @lukasbestle said on forum:

> Unfortunately no. Libraries that define the same helpers are not compatible with each other.

https://forum.getkirby.com/t/problem-using-blade-plugin/14853/28

> only solution seems to be to download this plugin to site/plugins or use git submodule as a way of includeing this plugin.

Exactly!

**Comment by adamkiss** [comment]
@afbora Do you think it's possible to just… not add the helpers? I'm not familiar enough with this codebase, but as I see it, composer installation right now just isn't really a viable option, since you can't ensure the order, right?

What actually uses the illuminate/support/helpers? Something internal, or is it available in templates? Otherwise, It'll be good idea to put a warning somewhere in the readme, I think. (I can PR that)

**Comment by iskrisis** [comment]
😢

**Comment by afbora** [comment]
I have great news for you 🎉 https://github.com/getkirby/kirby/pull/2829
