### ISSUE TITLE
Add support for snippet templates

### ISSUE THREAD

**Issue by hemorej** [afbora/kirby-blade#12]
Currently only blade templates that are present in the configured template directory (`/templates` by default) are compiled. Is it possible to support compiling templates from the snippets directory too?

All of the snippets are basically really short templates, they're just organized elsewhere. Right now, my template templates are in beautiful blade syntax and my snippet templates are still wrapper in hard to read php tags

**Comment by afbora** [comment]
@hemorej Did you try partials like that `@include("partials.note")`? Here sample template that contains snippets/partials:

https://github.com/afbora/kirby-blade/blob/master/templates/notes.blade.php

You can look out sample template directory:
https://github.com/afbora/kirby-blade#templates

**Comment by hemorej** [comment]
Ah of course I missed that. Thanks I'll try it out

**Comment by afbora** [comment]
Feel free reopen the issue if you need help.
