### ISSUE TITLE
Is it possible to register/use components?

### ISSUE THREAD

**Issue by iskrisis** [afbora/kirby-blade#13]
Is it possible to register/use components? Like here https://laravel.com/docs/7.x/blade#components ?

**Comment by afbora** [comment]
@iskrisis I have no idea for now, i'll take care 👍

**Comment by afbora** [comment]
@iskrisis Do you mean old usage like `@component('alert')` or new usage like `<x-alert />`?

**Comment by iskrisis** [comment]
Mostly ```<x-alert />``` but i would think both ways would work if component was registered. I am not sure where to do it or if it is even possible.

**Comment by afbora** [comment]
I tried to implement the new usage/register(component library) but I got some errors for now. But you can use the old method in current version as `@component('alert')`

Feel free create PR if you have a solution for new component usage 👍

**Comment by iskrisis** [comment]
Thanks for the info! I wasn't even aware i can use ```@component('alert')```

**Comment by afbora** [comment]
### Sample Usage

**/site/templates/default.blade.php**

````php
@component('components.alert')
    <strong>Whoops!</strong> Something went wrong!
@endcomponent
````

**/site/templates/components/alert.blade.php**

````php
<div class="alert alert-danger">
    {{ $slot }}
</div>
````

**Comment by adamkiss** [comment]
I'll just leave this here - https://github.com/jenssegers/blade/issues/49 - and maybe will look into it later.

**Comment by iskrisis** [comment]
I've been working with laravel lately and i really like the <x-component> I have no idea how to bring this to kirby. Are there any news on this? Could i maybe pay one of you for adding this @afbora @adamkiss ? Cheers

**Comment by afbora** [comment]
@iskrisis Have you look out?

https://github.com/beebmx/kirby-blade

**Comment by iskrisis** [comment]
@afbora amazing thanks!

**Comment by adamkiss** [comment]
@iskrisis I've used beebmx/kirby-blade and it works well enough - there was just a couple of issues between the blade and the content representations, if you use those. Otherwise, it works well.

**Comment by iskrisis** [comment]
👍

**Comment by RobertCordes** [comment]
PSA: I was having trouble using components the way @afbora described. Using his example, all tags would be escaped/written out. I had to change `{{ $slot }}` to `<?= $slot ?>`. Why this is working, I have no idea 🤣 But maybe it helps someone else.
