### ISSUE TITLE
Redeclared function error

### ISSUE THREAD

**Issue by Jonic** [afbora/kirby-blade#14]
I have Kirby and kirby-blade both installed via composer:

```
"require": {
    "php": ">=7.1.0",
    "afbora/kirby-blade": "^1.7",
    "getkirby/cms": "^3.0"
},
```

I've got a markdown file with a `title`, and the default blad template is outputting `<h1>@page('title')</h1>`

When I run my dev server I get the following error:

`Fatal error: Cannot redeclare e() (previously declared in /Users/[username]/Work/[repo]/vendor/illuminate/support/helpers.php:252) in /Users/[username]/Work/[repo]/kirby/config/helpers.php on line 160`

Any ideas how this is happening and how I might get around it?

**Comment by afbora** [comment]
@Jonic you can't use kirby-blade plugin from root composer. Related issue #11 
Download the last version and upload to `/site/plugins` folder to stable usage.

**Comment by afbora** [comment]
I have great news for you 🎉 https://github.com/getkirby/kirby/pull/2829
